export const SCOREBOARD_ADD_SCORE: string = 'SCOREBOARD_ADD_SCORE';
export const SCOREBOARD_RESET_SCORES: string = 'SCOREBOARD_RESET_SCORES';
export const SCOREBOARD_CHANGE_DIFFICULTY: string = 'SCOREBOARD_CHANGE_DIFFICULTY';
